const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.TextBox,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Zemin: 0},
	{baslik: 0},
	{Sine: 0},
	{btn_basla: 0},
	{Tween: 0},
	{infoyazi: 0},
	{btn_anasayfa: 0},
	{Touch: 0},
	{bg_oyun: 0},
	{sorular: 0},
	{yazialani: 0},
	{TextInput: 0},
	{dogruSay: 0},
	{score: 0},
	{score2: 0},
	{correct: 0},
	{wrong: 0},
	{score3: 0},
	{kontrol: 0},
	{Array: 0},
	{Browser: 0},
	{Keyboard: 0},
	{yanlisSay2: 0},
	{ok: 0},
	{Audio: 0},
	{Text: 0},
	{meblogo: 0},
	{bg_final: 0},
	{canHakki: 0},
	{btn_info: 0},
	{btn_kaynakca: 0},
	{btn_emgecen: 0},
	{btn_ekran: 0},
	{btn_sesac: 0},
	{btn_seskapat: 0},
	{bttn_tekraroyna: 0},
	{sure_halka: 0},
	{Sprite: 0},
	{buttons: 0},
	{infopage: 0},
	{cevap: 0},
	{dizi: 0},
	{dogruSayisi: 0},
	{yanlisSayisi: 0},
	{sure: 0},
	{cvphakki: 0},
	{cvplanansorular: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Zemin: class extends self.ISpriteInstance {},
	baslik: class extends self.ISpriteInstance {},
	btn_basla: class extends self.ISpriteInstance {},
	infoyazi: class extends self.ISpriteInstance {},
	btn_anasayfa: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	bg_oyun: class extends self.ISpriteInstance {},
	sorular: class extends self.ISpriteInstance {},
	yazialani: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	dogruSay: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteInstance {},
	score2: class extends self.ISpriteInstance {},
	correct: class extends self.ISpriteInstance {},
	wrong: class extends self.ISpriteInstance {},
	score3: class extends self.ISpriteInstance {},
	kontrol: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	yanlisSay2: class extends self.ISpriteInstance {},
	ok: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	meblogo: class extends self.ISpriteInstance {},
	bg_final: class extends self.ISpriteInstance {},
	canHakki: class extends self.ISpriteInstance {},
	btn_info: class extends self.ISpriteInstance {},
	btn_kaynakca: class extends self.ISpriteInstance {},
	btn_emgecen: class extends self.ISpriteInstance {},
	btn_ekran: class extends self.ISpriteInstance {},
	btn_sesac: class extends self.ISpriteInstance {},
	btn_seskapat: class extends self.ISpriteInstance {},
	bttn_tekraroyna: class extends self.ISpriteInstance {},
	sure_halka: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {}
}